spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRESDB_LOCAL_PORT}/${POSTGRESDB_DATABASE}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_ROOT_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  # # Настройки почты
  # mail:
  #   default-encoding: UTF-8
  #   host: smtp.gmail.com
  #   port: 465
  #   username: ${MAIL_USERNAME}
  #   password: ${MAIL_PASSWORD}
  #   protocol: smtps
  #   properties:
  #     mail:
  #       debug: true
  #       smtp:
  #         auth: true
  #         ssl:
  #           enable: true
  #           trust: smtp.gmail.com
  #         socketFactory:
  #           port: 465
  #           class: javax.net.ssl.SSLSocketFactory
  #           fallback: false
  #         connectiontimeout: 15000
  #         timeout: 15000
  #         writetimeout: 15000

  thymeleaf:
    cache: true
  compression:
    enabled: true

  # # Настройки инициализации БД
  # sql:
  #   init:
  #     mode: never
  #     continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

  # liquibase:
  #   change-log: classpath:db/changelog/db.changelog-master.xml
  #   enabled: true
  #   contexts: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 7638792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A
  expiration: 86400000 # 24 часа

# Конфигурация Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    back.client_exp_backend: DEBUG
    com.example.demo: DEBUG
